services:
  - type: worker
    name: sb24-wordflip-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_NAME
        value: SB24
      - key: BOT_USERNAME
        value: "@SBWordFlipBot"
